---
- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

# Setup/install tasks.
- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_deb_url }}"
    dest: "/tmp/{{ rabbitmq_deb }}"

- name: Ensure RabbitMQ is installed.
  apt:
    deb: "/tmp/{{ rabbitmq_deb }}"
    state: present
  ignore_errors: true

- name: Attente que RabbitMQ se lance proprement (en cas de montée de version)
  pause:
    seconds: 30

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
